export const INIT_GRID_PRODUCTOS = "INIT_GRID_PRODUCTOS"

export const READ_PRODUCTOS = "READ_PRODUCTOS";
export const READ_PRODUCTOS_OK = "READ_PRODUCTOS_OK";
export const READ_PRODUCTOS_ERROR = "READ_PRODUCTOS_ERROR";
export const READ_PRODUCTO = "READ_PRODUCTO";

export const READ_LOCALIZACIONES = "READ_LOCALIZACIONES";
export const READ_LOCALIZACIONES_OK = "READ_LOCALIZACIONES_OK";
export const READ_LOCALIZACIONES_ERROR = "READ_LOCALIZACIONES_ERROR";
export const READ_LOCALIZACION = "READ_LOCALIZACION";

export const READ_BODEGAS = "READ_BODEGAS";
export const READ_BODEGAS_OK = "READ_BODEGAS_OK";
export const READ_BODEGAS_ERROR = "READ_BODEGAS_ERROR";
export const READ_BODEGA = "READ_BODEGA";

export const READ_POSICIONES_BODEGAS = "READ_POSICIONES_BODEGAS";
export const READ_POSICIONES_BODEGAS_OK = "READ_POSICIONES_BODEGAS_OK";
export const READ_POSICIONES_BODEGAS_ERROR = "READ_BODEGAS_ERROR";
export const READ_POSICIONES_BODEGA = "READ_POSICIONES_BODEGAS";

export const READ_ENVASES = "READ_ENVASES";
export const READ_ENVASES_OK = "READ_ENVASES_OK";
export const READ_ENVASES_ERROR = "READ_ENVASES_ERROR";
export const READ_ENVASE = "READ_ENVASE";

export const READ_CONDICIONES = "READ_CONDICIONES";
export const READ_CONDICIONES_OK = "READ_CONDICIONES_OK";
export const READ_CONDICIONES_ERROR = "READ_CONDICIONES_ERROR";
export const READ_CONDICION = "READ_CONDICION";

export const READ_DEFECTOS = "READ_DEFECTOS";
export const READ_DEFECTOS_OK = "READ_DEFECTOS_OK";
export const READ_DEFECTOS_ERROR = "READ_DEFECTOS_ERROR";
export const READ_DEFECTO = "READ_DEFECTO";

export const CREATE_PRODUCTO = "CREATE_PRODUCTO";
export const UPDATE_PRODUCTOS = "UPDATE_PRODUCTOS";
export const DELETE_PRODUCTOS = "DELETE_PRODUCTOS";

export const READ_USUARIOS = "READ_USUARIOS";
export const READ_USUARIOS_OK = "READ_USUARIOS_OK";
export const READ_USUARIOS_ERROR = "READ_USUARIOS_ERROR";
export const READ_USUARIO = "READ_USUARIO";

export const READ_TRANSPORTISTAS = "READ_TRANSPORTISTAS";
export const READ_TRANSPORTISTAS_OK = "READ_TRANSPORTISTAS_OK";
export const READ_TRANSPORTISTAS_ERROR = "READ_TRANSPORTISTAS_ERROR";
export const READ_TRANSPORTISTA = "READ_TRANSPORTISTA";

export const READ_LUGARREVISIONES = "READ_LUGARREVISIONES";
export const READ_LUGARREVISIONES_OK = "READ_LUGARREVISIONES_OK";
export const READ_LUGARREVISIONES_ERROR = "READ_LUGARREVISIONES_ERROR";
export const READ_LUGARREVISION = "READ_LUGARREVISION";

export const READ_TIPOCONTENEDORES = "READ_TIPOCONTENEDORES";
export const READ_TIPOCONTENEDORES_OK = "READ_TIPOCONTENEDORES_OK";
export const READ_TIPOCONTENEDORES_ERROR = "READ_TIPOCONTENEDORES_ERROR";
export const READ_TIPOCONTENEDOR = "READ_TIPOCONTENEDOR";

export const READ_CONTENEDORESESTATUSES = "READ_CONTENEDORESESTATUSES";
export const READ_CONTENEDORESESTATUSES_OK = "READ_CONTENEDORESESTATUSES_OK";
export const READ_CONTENEDORESESTATUSES_ERROR = "READ_CONTENEDORESESTATUSES_ERROR";
export const READ_CONTENEDORESESTATUS = "READ_CONTENEDORESESTATUS";

export const READ_PERSONALAPOYOPERFILES = "READ_PERSONALAPOYOPERFILES";
export const READ_PERSONALAPOYOPERFILES_OK = "READ_PERSONALAPOYOPERFILES_OK";
export const READ_PERSONALAPOYOPERFILES_ERROR = "READ_PERSONALAPOYOPERFILES_ERROR";
export const READ_PERSONALAPOYOPERFIL = "READ_PERSONALAPOYOPERFIL";

export const READ_PERSONALAPOYOS = "READ_PERSONALAPOYOS";
export const READ_PERSONALAPOYOS_OK = "READ_PERSONALAPOYOS_OK";
export const READ_PERSONALAPOYOS_ERROR = "READ_PERSONALAPOYOS_ERROR";
export const READ_PERSONALAPOYO = "READ_PERSONALAPOYO";
